services:
  postgres:
    image: postgres:latest
    container_name: fastapi_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - app-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    image: backend
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000

volumes:
  app-db-data: