services:
  postgres:
    image: postgres:latest
    container_name: fastapi_postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - my_pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
volumes:
  my_pgdata: